version: "2.4"
services:
  postgres:
    image: postgres:13
    ports:
      - "15432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U discount" ]
      interval: 5s
      timeout: 10s
      retries: 15
    environment:
      POSTGRES_DB: starwars
      POSTGRES_USER: starwars
      POSTGRES_PASSWORD: P@ssword

  migration:
    image: migrate/migrate:v4.14.1
    command: ["-path=/migrations", "-database=postgres://starwars:P@ssword@postgres:5432/starwars?sslmode=disable", "up"]
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./infrastructure/migrations:/migrations